language: python
python:
  - "2.7"
script: py.test
before_install:
  - pip install codecov
install:
  - python setup.py install --record installed_files.txt
after_success:
  - codecov -t ${CODECOV_TOKEN}