language: python
python:
  - "2.7"
script: py.test
before_install:
  - pip install --user codecov
install:
  - python setup.py install --record installed_files.txt
after_success:
  - codecov --file coverage/lcov.info --disable search